name: Create Linux VPS (SSH)

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 1440

    steps:
      

      - name: Install tmate
        run: |
          sudo apt install -y tmate

      - name: Start SSH session
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "SSH session ready!"

          echo "================ SSH LOGIN ================"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "==========================================="

          echo "Keeping session alive..."
          while true; do sleep 300; done
